import React from 'react';

const page = () => {
    return (
        <div className='pt-16'>
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Magnam quibusdam nesciunt, commodi sequi natus magni non, dolore pariatur tempore expedita repellendus veritatis molestiae laboriosam, modi ipsa facere laborum eaque esse!
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quis eligendi maxime porro. Mollitia, labore. Dolore, hic asperiores! Excepturi similique rerum libero maiores? Commodi neque quasi porro laborum voluptate maiores? Omnis quasi asperiores provident obcaecati libero harum. Pariatur, sed ratione! Aspernatur dignissimos adipisci maxime esse voluptatem soluta numquam natus, doloribus officiis consequatur molestiae in omnis tempora tempore laboriosam commodi doloremque labore beatae. Soluta optio debitis dolorem asperiores? Debitis aliquam libero culpa. Amet pariatur facilis hic excepturi, autem nemo quaerat rerum quod nulla rem eius quisquam illum sit molestiae cupiditate sed facere voluptatem doloremque repellendus fugiat ducimus eum iste officia quis. Numquam et error porro minus necessitatibus neque sit ea. Perferendis nihil cupiditate nesciunt aliquam sequi nam maiores temporibus non ducimus, iure suscipit nostrum expedita officia quam quasi nulla incidunt minus, aliquid consequuntur fugit impedit, harum hic. Mollitia sequi, reiciendis quasi dolores natus, ea voluptatem blanditiis sunt optio placeat deleniti recusandae nesciunt aspernatur in tempore, consequatur corrupti labore modi minus nostrum facilis laborum. Dolores, quod commodi. Eaque nihil modi provident maxime sunt quibusdam iusto cupiditate expedita assumenda odio, nisi unde consequuntur facilis, aperiam error necessitatibus laboriosam veritatis sint. Hic consectetur doloribus ut eligendi neque blanditiis aliquid, non et ab, laboriosam quidem laudantium ad impedit dolorum delectus adipisci, distinctio magni inventore dolor consequuntur qui. Necessitatibus voluptatibus deleniti dolor, quisquam perferendis unde blanditiis dolore quo vero vitae, consectetur ipsa eius. Ut esse, qui repellendus molestias quod inventore soluta ipsa porro architecto, dicta ad illo! Officia numquam quia placeat quas reiciendis odio voluptatibus tenetur vero, nihil, voluptate ipsam atque praesentium consequatur libero repudiandae natus quasi iste nam fuga nobis voluptatum vel! Quo cumque, magni nulla molestiae dolores maxime expedita dolorem? Repudiandae culpa expedita modi deserunt dolor, quaerat odio sequi laudantium dolorum a nisi cum porro corrupti atque itaque beatae distinctio aspernatur? Nulla pariatur ducimus maxime.
        </div>
    );
};

export default page;